package com.zenlocare.clinics.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "invitations")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Invitation {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "invitation_id")
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hospital_id", nullable = false)
    private Hospital hospital;

    @Column(name = "invited_email", nullable = false, length = 255)
    private String invitedEmail;

    @Column(nullable = false, length = 50)
    private String role; // role name to be assigned on acceptance

    @Column(nullable = false, unique = true, length = 255)
    private String token; // UUID generated by app

    @Column(nullable = false, length = 20)
    @Builder.Default
    private String status = "PENDING"; // PENDING | ACCEPTED | EXPIRED

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    private User createdBy; // User who sent the invitation

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @Builder.Default
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @PrePersist
    public void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
        normalizeCase();
    }

    @PreUpdate
    public void onUpdate() {
        normalizeCase();
    }

    private void normalizeCase() {
        if (invitedEmail != null) {
            this.invitedEmail = invitedEmail.toLowerCase().trim();
        }
    }
}
