import { Spinner } from "@/components/ui/Loader";
import { useState, useEffect, useMemo } from 'react'
import axios from 'axios'
import SSOCookieManager from '@/utils/ssoManager'
import SearchableSelect from '@/components/ui/SearchableSelect'
import { invoiceApi, bankApi, hospitalServiceApi, patientServicesApi, radiologyApi, ambulanceApi, patientAdvanceApi, claimsApi } from '@/utils/api'
import InvoiceDeductionNote from '@/components/billing/InvoiceDeductionNote'
import { useAuth } from '@/context/AuthContext'
import { useNotification } from '@/context/NotificationContext'
import { generateInvoiceNumber } from '@/utils/validators'
import { fmtId } from '@/utils/idFormat'
import { X, Receipt, AlertCircle, Plus, Trash2, BedDouble, ScanLine, Stethoscope, Pill, FlaskConical, Wrench, Scissors, Landmark, Wallet, IndianRupee, Clock, UserCheck, Ambulance,  } from "lucide-react";

const PAYMENT_METHODS = ['Cash', 'UPI', 'Card', 'Bank Transfer', 'Insurance']
const GST_RATE = 0.18

// Cash → CASH-type drawer; UPI/Card/Bank Transfer → SAVINGS or CURRENT.
// Insurance is settled separately; no on-the-spot account credit.
const PAYMENT_METHOD_TO_ACCOUNT_TYPES = {
  'Cash':          ['CASH'],
  'UPI':           ['SAVINGS', 'CURRENT'],
  'Card':          ['SAVINGS', 'CURRENT'],
  'Bank Transfer': ['SAVINGS', 'CURRENT'],
  'Insurance':     [],
}

function accountsForMethod(accounts, method) {
  const allowed = PAYMENT_METHOD_TO_ACCOUNT_TYPES[method] || []
  if (allowed.length === 0) return []
  return (accounts || []).filter(a => allowed.includes((a.accountType || '').toUpperCase()))
}

const TYPE_META = {
  ROOM_CHARGE:  { label: 'Room',         icon: BedDouble   },
  CONSULTATION: { label: 'Consultation', icon: Stethoscope },
  RADIOLOGY:    { label: 'Radiology',    icon: ScanLine    },
  LAB_TEST:     { label: 'Lab Test',     icon: FlaskConical},
  MEDICINE:     { label: 'Medicine',     icon: Pill        },
  OT:           { label: 'OT / Surgery', icon: Scissors    },
  CUSTOM:       { label: 'Custom',       icon: Wrench      },
  REGISTRATION: { label: 'Registration', icon: UserCheck   },
  AMBULANCE:    { label: 'Ambulance',    icon: Ambulance   },
}

const otApi = axios.create({ baseURL: 'https://api-ot.zenohosp.com', withCredentials: true })
otApi.interceptors.request.use(config => {
  const token = SSOCookieManager.getToken()
  if (token) config.headers.Authorization = `Bearer ${token}`
  return config
})

// Mirror of the OT integration — pulls finalised pharmacy bills (HMS_CREDIT
// only; CASH is excluded server-side because it's already collected) for an
// admission. Dedupe is on bill id, persisted by the backend on
// invoice_items.pharmacy_bill_id so reloads don't double-charge.
const pharmacyApi = axios.create({ baseURL: 'https://api-pharmacy.zenohosp.com', withCredentials: true })
pharmacyApi.interceptors.request.use(config => {
  const token = SSOCookieManager.getToken()
  if (token) config.headers.Authorization = `Bearer ${token}`
  return config
})

function fmt(n) {
  return '₹' + Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function fmtTime(iso) {
  if (!iso) return ''
  return new Date(iso).toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata', day: '2-digit', month: 'short',
    hour: '2-digit', minute: '2-digit', hour12: true,
  })
}

// CUSTOM items in the IPD invoice come from two distinct sources:
//   1. Auto-calculated charges built fresh each time the modal opens — food,
//      patient services (daily/one-time), ambulance bookings.
//   2. User-entered free-text items (e.g. "Extra bedsheets", "Maintenance fee").
//
// On reload we must drop (1) so it can be regenerated with current quantities,
// but preserve (2) verbatim. The bill stores no metadata distinguishing them,
// so we infer from the description shape.
//
// Auto patterns (must match exactly — see the auto-build loop further down):
//   • "Ambulance"            — bare type, no vehicle
//   • "Ambulance — …"        — type/vehicle composed via " — " separator
//   • "<service.name>"       — one-time charge (registration, custom one-time)
//   • "<service.name> (N meal)" / "(N meals)" — FOOD service
//   • "<service.name> (N day)"  / "(N days)"  — daily-rate service
//
// Anything else is user-entered and survives the reload.
function isAutoGeneratedCustomDescription(description, patientServicesList) {
  if (!description) return false
  if (description === 'Ambulance' || description.startsWith('Ambulance — ')) return true
  if (!Array.isArray(patientServicesList)) return false
  for (const svc of patientServicesList) {
    if (!svc?.isActive || !svc.name) continue
    const name = svc.name
    if (description === name) return true
    // " (N meal)", " (N meals)", " (N day)", " (N days)" suffix
    if (description.startsWith(name + ' (')) {
      const tail = description.slice(name.length + 2, -1)  // strip "<name> (" and trailing ")"
      if (/^\d+ (meal|meals|day|days)$/.test(tail)) return true
    }
  }
  return false
}

function countMealSlots(admitDate, dischargeDate, chargeTime) {
  if (!chargeTime) return 0
  const [h, m] = chargeTime.split(':').map(Number)
  const admit = new Date(admitDate)
  const discharge = new Date(dischargeDate)
  let count = 0
  const day = new Date(admit)
  day.setHours(0, 0, 0, 0)
  while (day <= discharge) {
    const slot = new Date(day)
    slot.setHours(h, m, 0, 0)
    if (slot >= admit && slot <= discharge) count++
    day.setDate(day.getDate() + 1)
  }
  return count
}

export default function FinalizeIPDBillingModal({ admission, onClose, onFinalized }) {
  const { user } = useAuth()
  const { notify } = useNotification()

  const [invoiceId, setInvoiceId] = useState(null)
  const [invoiceStatus, setInvoiceStatus] = useState('UNSETTLED')
  const [loadingBill, setLoadingBill] = useState(true)
  // Names of finance-critical charge sources (OT, Pharmacy) whose fetch failed
  // during load. Their charges are best-effort pulls; if a source is unreachable
  // it silently returns nothing, so we surface this to stop the biller finalizing
  // a bill that's silently missing those charges.
  const [chargeLoadWarnings, setChargeLoadWarnings] = useState([])
  const [items, setItems] = useState([])
  const [nextKey, setNextKey] = useState(0)
  const [discountPct, setDiscountPct] = useState(0)
  const [bankAccounts, setBankAccounts] = useState([])
  const [billNotes, setBillNotes] = useState('')
  const [advances, setAdvances] = useState([])
  const [existingPayments, setExistingPayments] = useState([])

  // Collect payment section
  const [payAmount, setPayAmount] = useState('')
  const [payMethod, setPayMethod] = useState('Cash')
  const [payBankAccountId, setPayBankAccountId] = useState('')

  const [savingBill, setSavingBill] = useState(false)
  const [collectingPayment, setCollectingPayment] = useState(false)
  const [fallbackInvoiceNo] = useState(generateInvoiceNumber)
  // dirty = true once any save/payment hits the server. Lets the parent skip a
  // refetch (and the flicker that comes with it) when the user just opened the
  // modal to view and closed it without making changes.
  const [dirty, setDirty] = useState(false)

  // Credit patient early payment override
  const [showEarlyCollect, setShowEarlyCollect] = useState(false)

  const effectiveDischargeDate = new Date().toISOString()

  useEffect(() => {
    if (!user?.hospitalId || !admission.patientId) return
    setLoadingBill(true)

    const admitMs = new Date(admission.admissionDate).getTime()
    const dischargeMs = new Date(effectiveDischargeDate).getTime()
    const elapsedMs = dischargeMs - admitMs
    const roomDays = Math.floor(elapsedMs / (1000 * 60 * 60 * 24))

    Promise.all([
      invoiceApi.getSmartSuggestions(admission.patientId, admission.id).catch(() => ({})),
      hospitalServiceApi.list(user.hospitalId).catch(() => []),
      bankApi.list(user.hospitalId).catch(() => []),
      radiologyApi.getByAdmission(admission.id).catch(() => []),
      patientServicesApi.list(user.hospitalId).catch(() => []),
      otApi.get('/api/ot/invoices', { params: { admissionId: admission.id } }).catch(() => ({ data: [], __loadFailed: true })),
      invoiceApi.getAdmissionInvoice(admission.id).catch(() => null),
      ambulanceApi.getBookings(user.hospitalId).catch(() => []),
      patientAdvanceApi.listForAdmission(admission.id).catch(() => []),
      invoiceApi.getPatientInvoices(admission.patientId).catch(() => []),
      pharmacyApi.get('/api/pharmacy/bills', { params: { admissionId: admission.id, unbilled: true } }).catch(() => ({ data: [], __loadFailed: true })),
    ]).then(([suggestions, services, accounts, radiologyOrders, patientServices, otRes, existingInvoice, ambulanceBookings, advanceList, allPatientInvoices, pharmacyRes]) => {
      // Flag any finance-critical source that failed to load so the biller is
      // warned its charges may be missing (rather than silently finalizing without them).
      const chargeWarns = []
      if (otRes?.__loadFailed) chargeWarns.push('OT / Surgery')
      if (pharmacyRes?.__loadFailed) chargeWarns.push('Pharmacy')
      setChargeLoadWarnings(chargeWarns)

      const isFirstAdmission = (allPatientInvoices || []).filter(inv =>
        inv.admissionId && String(inv.admissionId) !== String(admission.id)
      ).length === 0
      setBankAccounts(accounts)
      // Pre-select an account matching the initial payment method (Cash by default)
      const eligible = accountsForMethod(accounts, 'Cash')
      const def = eligible.find(a => a.isDefault) ?? eligible[0]
      if (def) setPayBankAccountId(def.id)

      if (existingInvoice?.id) {
        setInvoiceId(existingInvoice.id)
        setInvoiceStatus(existingInvoice.status || 'UNSETTLED')
        setExistingPayments(existingInvoice.payments || [])
        if (existingInvoice.notes) setBillNotes(existingInvoice.notes)
        // Recalculate discount % from saved values
        if (existingInvoice.subtotal > 0 && existingInvoice.discount > 0) {
          setDiscountPct(Math.round((existingInvoice.discount / existingInvoice.subtotal) * 100))
        }
      }
      setAdvances(Array.isArray(advanceList) ? advanceList : [])

      // ── Build item list ───────────────────────────────────────────────────────
      let key = 0
      const savedItems = []

      // Identifiers already committed to the bill
      const savedAppointmentIds = new Set()
      const savedRadiologyIds = new Set()
      const savedOTDescriptions = new Set()
      // Stable per-line UUID from OTM (preferred over description for
      // dedup so editing the description doesn't re-pull a fresh copy).
      const savedOTInvoiceItemIds = new Set()
      const savedOTBookingIds = new Set()
      const savedAmbulanceIds = new Set()
      // Pharmacy bills carry a real UUID — dedupe by id, not description, so
      // repeated drug names across visits don't collide. Server persists
      // invoice_items.pharmacy_bill_id on each save; we read it back here.
      const savedPharmacyBillIds = new Set()
      const hasRoomCharge = { value: false }
      const hasCustomDesc = new Set()

      if (existingInvoice?.items?.length > 0) {
        existingInvoice.items.forEach(item => {
          const entry = {
            key: key++,
            itemType: item.itemType,
            description: item.description,
            quantity: item.quantity,
            unitPrice: Number(item.unitPrice || 0),
            totalPrice: Number(item.totalPrice || 0),
            appointmentId: item.appointmentId ?? undefined,
            radiologyOrderId: item.radiologyOrderId ?? undefined,
            ambulanceBookingId: item.ambulanceBookingId ?? undefined,
            pharmacyBillId: item.pharmacyBillId ?? undefined,
            // Carry the OT identifiers through so re-saves don't lose them.
            // Without this, the second save after a reload would drop the
            // stable UUID and fall back to description-keyed dedup.
            otInvoiceItemId: item.otInvoiceItemId ?? undefined,
            otBookingId: item.otBookingId ?? undefined,
            // Pharmacy-sourced MEDICINE rows are stored with GST already
            // baked in (see the pharmacy-pull section below). Re-flag them
            // on reload so the HMS GST calc continues to skip them.
            gstInclusive: !!item.pharmacyBillId,
            fromOpd: false,
          }

          if (item.itemType === 'ROOM_CHARGE') {
            // Room/food: always replaced with fresh calculation — skip saving
            hasRoomCharge.value = true
            return
          }
          if (item.itemType === 'CUSTOM') {
            // CUSTOM is the catch-all type used for both auto-calculated charges
            // (food, patient services, ambulance) AND user-entered free-text
            // items (e.g. "Extra bedsheets ₹500"). The auto-calculated ones must
            // be discarded here so the loop below can regenerate them with
            // fresh quantities — but user-entered ones must survive the reload.
            //
            // Heuristic: a description that matches one of the auto-generation
            // patterns is treated as auto and dropped; everything else is
            // preserved as user-entered.
            if (isAutoGeneratedCustomDescription(item.description, patientServices)) {
              hasCustomDesc.add(item.description)
              return
            }
            entry.isUserCustom = true
            savedItems.push(entry)
            return
          }
          if (item.itemType === 'CONSULTATION' && item.appointmentId) {
            savedAppointmentIds.add(String(item.appointmentId))
            const isOpd = existingInvoice.admissionNumber &&
              item.description?.toLowerCase().includes('consultation')
            entry.fromOpd = isOpd && savedAppointmentIds.size === 1
          }
          if (item.itemType === 'RADIOLOGY' && item.radiologyOrderId) {
            savedRadiologyIds.add(String(item.radiologyOrderId))
          }
          if (item.itemType === 'OT') {
            savedOTDescriptions.add(item.description)
            if (item.otInvoiceItemId) savedOTInvoiceItemIds.add(String(item.otInvoiceItemId))
            if (item.otBookingId)     savedOTBookingIds.add(String(item.otBookingId))
          }
          if (item.ambulanceBookingId) {
            savedAmbulanceIds.add(String(item.ambulanceBookingId))
          }
          if (item.pharmacyBillId) {
            savedPharmacyBillIds.add(String(item.pharmacyBillId))
          }
          savedItems.push(entry)
        })
      }

      const auto = [...savedItems]

      // Room charge — recalculate current total days
      const roomNumber = admission.roomNumber
      if (roomNumber && roomDays > 0) {
        const pricePerDay = suggestions.roomCharge?.pricePerDay || admission.roomPricePerDay || 0
        const roomType = admission.roomType
        const roomLabel = roomType ? `Room ${roomNumber} (${roomType.replace(/_/g, ' ')})` : `Room ${roomNumber}`
        auto.push({
          key: key++, itemType: 'ROOM_CHARGE',
          description: `${roomLabel} — ${roomDays} day${roomDays !== 1 ? 's' : ''}`,
          quantity: roomDays, unitPrice: pricePerDay, totalPrice: roomDays * pricePerDay,
        })
      }

      // Consultations — skip already saved by appointmentId
      const carriedAppointmentIds = new Set(auto.filter(i => i.appointmentId).map(i => String(i.appointmentId)))
      ;(suggestions.appointments || []).forEach(a => {
        if (carriedAppointmentIds.has(String(a.appointmentId))) return
        if (savedAppointmentIds.has(String(a.appointmentId))) return
        auto.push({
          key: key++, itemType: 'CONSULTATION',
          description: `Consultation — Dr. ${a.doctorName}${a.specialization ? ` (${a.specialization})` : ''}`,
          quantity: 1, unitPrice: a.consultationFee, totalPrice: a.consultationFee,
          appointmentId: a.appointmentId,
        })
      })

      // Radiology — skip already saved
      const EXCLUDED = ['CANCELLED', 'BILLED']
      ;(Array.isArray(radiologyOrders) ? radiologyOrders.filter(r => !EXCLUDED.includes(r.status)) : []).forEach(r => {
        if (savedRadiologyIds.has(String(r.id))) return
        const name = r.serviceName || r.investigationName || r.testName || 'Radiology'
        const match = services.find(s => s.name.toLowerCase() === name.toLowerCase())
        const price = match?.price ?? 0
        auto.push({
          key: key++, itemType: 'RADIOLOGY', description: name,
          quantity: 1, unitPrice: price, totalPrice: price, radiologyOrderId: r.id,
        })
      })

      // Patient services (food + others) — recalculate fresh quantities.
      // A zero-quantity line (e.g. admitted at 23:26 with dinner at 20:00, so no
      // meal slot has occurred yet) is skipped entirely rather than pushed as a
      // ₹0 row — otherwise the bill shows "Dinner (0 meals) ₹0" which reads to
      // staff as "dinner is being charged."
      ;(Array.isArray(patientServices) ? patientServices.filter(s => s.isActive) : []).forEach(s => {
        if (s.type === 'FOOD') {
          const price = s.pricePerMeal || 0
          const quantity = s.chargeTime
            ? countMealSlots(admission.admissionDate, effectiveDischargeDate, s.chargeTime)
            : roomDays * 3
          if (quantity <= 0) return
          auto.push({
            key: key++, itemType: 'CUSTOM',
            description: `${s.name} (${quantity} meal${quantity !== 1 ? 's' : ''})`,
            quantity, unitPrice: price, totalPrice: quantity * price,
          })
        } else if (s.type === 'REGISTRATION' && s.oneTimeCharge) {
          // Skip if backend already added a REGISTRATION item to the invoice
          const backendAlreadyCharged = savedItems.some(i => i.itemType === 'REGISTRATION')
          if (isFirstAdmission && !backendAlreadyCharged) {
            const price = s.pricePerDay || 0
            auto.push({ key: key++, itemType: 'CUSTOM', description: s.name, quantity: 1, unitPrice: price, totalPrice: price })
          }
        } else if (s.oneTimeCharge) {
          const price = s.pricePerDay || 0
          auto.push({ key: key++, itemType: 'CUSTOM', description: s.name, quantity: 1, unitPrice: price, totalPrice: price })
        } else {
          const price = s.pricePerDay || 0
          const qty = s.chargeTime
            ? countMealSlots(admission.admissionDate, effectiveDischargeDate, s.chargeTime)
            : roomDays
          if (qty <= 0) return
          auto.push({
            key: key++, itemType: 'CUSTOM',
            description: `${s.name} (${qty} day${qty !== 1 ? 's' : ''})`,
            quantity: qty, unitPrice: price, totalPrice: qty * price,
          })
        }
      })

      // Ambulance — skip already saved
      const admitDay = new Date(admission.admissionDate)
      admitDay.setHours(0, 0, 0, 0)
      const dayBefore = new Date(admitDay)
      dayBefore.setDate(dayBefore.getDate() - 1)
      ;(Array.isArray(ambulanceBookings) ? ambulanceBookings : [])
        .filter(b => {
          const pid = b.patient?.id ?? b.patientId
          if (String(pid) !== String(admission.patientId)) return false
          if (b.status !== 'COMPLETED') return false
          if (b.paymentStatus === 'PAID') return false
          if (savedAmbulanceIds.has(String(b.id))) return false
          const bDate = new Date(b.bookingDate)
          return bDate >= dayBefore
        })
        .forEach(b => {
          const typeName = b.ambulanceType?.name || ''
          const vehicleNo = b.vehicle?.vehicleNumber || b.vehicleNumber || ''
          const desc = ['Ambulance', typeName, vehicleNo].filter(Boolean).join(' — ')
          const charge = Number(b.charge || 0)
          auto.push({
            key: key++, itemType: 'CUSTOM', description: desc,
            quantity: 1, unitPrice: charge, totalPrice: charge,
            ambulanceBookingId: b.id,
          })
        })

      // OT charges — prefer the stable per-line UUID for dedup; fall back
      // to description only for legacy rows saved before OTM started
      // sending otInvoiceItemId. Compute unitPrice as totalPrice / quantity
      // so an edit to qty doesn't double the line (the old code stored
      // totalPrice into unitPrice, which then re-multiplied by quantity).
      ;(Array.isArray(otRes?.data) ? otRes.data : []).forEach(inv => {
        ;(Array.isArray(inv.items) ? inv.items : []).forEach(item => {
          const id   = item.otInvoiceItemId ? String(item.otInvoiceItemId) : null
          const desc = item.description || item.name || 'OT Procedure'

          // ID match wins. Description only for legacy rows (no id).
          if (id && savedOTInvoiceItemIds.has(id)) return
          if (!id && savedOTDescriptions.has(desc)) return

          const qty   = Number(item.quantity ?? 1) || 1
          const total = Number(item.totalPrice ?? item.amount ?? 0) || 0
          const unit  = qty > 0 ? total / qty : total

          auto.push({
            key: key++, itemType: 'OT', description: desc,
            quantity: qty, unitPrice: unit, totalPrice: total,
            otBookingId:     inv.bookingId        ?? null,
            otInvoiceItemId: item.otInvoiceItemId ?? null,
          })
        })
      })

      // Pharmacy bills — each bill explodes into one MEDICINE row per
      // dispensed drug. Dedupe on bill id so reloads after a partial save
      // don't double-bill. unbilled=true on the pull already hides CASH and
      // any legacy-pushed rows.
      //
      // GST handling: pharmacy already applied tax on its side (mixed rates
      // per drug — 5%, 12%, 18%, all GST-inclusive in bill.totalAmount).
      // HMS would otherwise sum pre-tax line totalPrice and uniformly apply
      // 18% on top, which silently under- or over-bills depending on the
      // drug mix. Instead we proportionally distribute bill.totalAmount
      // across each line so the sum of MEDICINE rows from one bill exactly
      // matches the pharmacy's authoritative total. Lines are tagged
      // gstInclusive so the HMS-side GST calc below skips them.
      ;(Array.isArray(pharmacyRes?.data) ? pharmacyRes.data : []).forEach(bill => {
        if (!bill?.id || savedPharmacyBillIds.has(String(bill.id))) return
        const lines = Array.isArray(bill.items) ? bill.items : []
        const preGstSum = lines.reduce((s, l) => {
          const q = Number(l.quantity ?? 1) || 1
          const u = Number(l.unitPrice ?? 0) || 0
          return s + (Number(l.totalPrice ?? u * q) || 0)
        }, 0)
        const billTotal = Number(bill.totalAmount ?? 0) || 0
        const factor = preGstSum > 0 ? billTotal / preGstSum : 1
        const billNo = bill.billNumber ? ` · ${bill.billNumber}` : ''
        lines.forEach(line => {
          const qty = Number(line.quantity ?? 1) || 1
          const unit = Number(line.unitPrice ?? 0) || 0
          const preGst = Number(line.totalPrice ?? unit * qty) || 0
          const inclusive = preGst * factor
          auto.push({
            key: key++, itemType: 'MEDICINE',
            description: `${line.drugName || 'Medicine'}${billNo}`,
            quantity: qty,
            // Show inclusive unit price so the row's own qty × unit reconciles
            // visually with the displayed totalPrice.
            unitPrice: qty > 0 ? inclusive / qty : 0,
            totalPrice: inclusive,
            pharmacyBillId: bill.id,
            gstInclusive: true,
          })
        })
      })

      setItems(auto.filter(i => Number(i.quantity) > 0 || Number(i.totalPrice) > 0))
      setNextKey(key)

    }).catch(() => {
      notify('Could not load pending charges — add items manually', 'info')
    }).finally(() => setLoadingBill(false))
  }, [admission.id, user?.hospitalId])

  const addBlankItem = () => {
    setItems(prev => [...prev, { key: nextKey, itemType: 'CUSTOM', description: '', quantity: 1, unitPrice: 0, totalPrice: 0 }])
    setNextKey(k => k + 1)
  }
  const removeItem = key => setItems(prev => prev.filter(i => i.key !== key))
  const updateItem = (key, updates) => {
    setItems(prev => prev.map(item => {
      if (item.key !== key) return item
      const merged = { ...item, ...updates }
      if ('quantity' in updates || 'unitPrice' in updates)
        merged.totalPrice = (Number(merged.quantity) || 0) * (Number(merged.unitPrice) || 0)
      return merged
    }))
  }

  const subtotal = useMemo(() => items.reduce((s, i) => s + (i.totalPrice || 0), 0), [items])
  const discountAmt = subtotal * (discountPct / 100)
  // GST applies only to MEDICINE rows that HMS itself is taxing. Pharmacy-
  // sourced rows arrive GST-inclusive (the pharmacy applies per-drug rates
  // server-side and we distribute the bill's totalAmount across lines), so
  // they're flagged gstInclusive and excluded from the HMS tax base.
  const medicineSubtotal = useMemo(
    () => items
      .filter(i => i.itemType === 'MEDICINE' && !i.gstInclusive)
      .reduce((s, i) => s + (i.totalPrice || 0), 0),
    [items]
  )
  const gst = (medicineSubtotal - medicineSubtotal * (discountPct / 100)) * GST_RATE
  const grandTotal = subtotal - discountAmt + gst

  // Silently keep billing list estimate in sync as items load/change
  useEffect(() => {
    if (!invoiceId || loadingBill || grandTotal <= 0) return
    invoiceApi.updateEstimate(invoiceId, grandTotal).catch(() => {})
  }, [grandTotal, invoiceId, loadingBill])

  // Remaining advance = total collected minus already applied portions
  const totalAdvance = useMemo(
    () => advances.reduce((s, a) => s + Math.max(0, Number(a.amount || 0) - Number(a.appliedAmount || 0)), 0),
    [advances]
  )
  const advanceAdjusted = Math.min(totalAdvance, grandTotal)
  // What stays in the patient's advance wallet once this bill takes its share —
  // a ₹20,000 advance against a ₹1,500 bill leaves ₹18,500 for later bills or
  // refund at discharge. Shown explicitly so the cashier never has to subtract.
  const advanceRemaining = Math.max(0, totalAdvance - advanceAdjusted)

  // Total cash collected so far (from payment history)
  const totalCashPaid = useMemo(
    () => existingPayments.reduce((s, p) => s + Number(p.amount || 0), 0),
    [existingPayments]
  )
  const balanceDue = Math.max(0, grandTotal - advanceAdjusted - totalCashPaid)

  // Active insurance/TPA claim on this invoice. Only APPROVED / PARTIALLY_APPROVED
  // amounts reduce what the patient owes right now — a SETTLED claim's money is
  // already inside paidAmount (settlement records an Insurance payment), and a
  // submitted claim is not yet the payer's commitment.
  const [invoiceClaim, setInvoiceClaim] = useState(null)
  useEffect(() => {
    if (!invoiceId || !user?.hospitalId) { setInvoiceClaim(null); return }
    let cancelled = false
    claimsApi.list(user.hospitalId)
      .then(data => {
        if (cancelled) return
        const claim = (data?.claims || []).find(c => String(c.invoiceId) === String(invoiceId)) || null
        setInvoiceClaim(claim)
      })
      .catch(() => { /* optional context */ })
    return () => { cancelled = true }
  }, [invoiceId, user?.hospitalId])
  const claimExpected = ['APPROVED', 'PARTIALLY_APPROVED'].includes(invoiceClaim?.status)
    ? Math.min(Number(invoiceClaim.approvedAmount || 0), balanceDue)
    : 0
  const patientShare = Math.max(0, balanceDue - claimExpected)

  const hasZeroPrice = items.some(i => Number(i.unitPrice) === 0 && i.itemType !== 'CUSTOM')
  const hasOpdCarryOver = useMemo(() => items.some(i => i.fromOpd), [items])

  const buildPayload = () => ({
    invoiceNumber: fallbackInvoiceNo,
    hospitalId: user.hospitalId,
    patientId: admission.patientId,
    admissionId: admission.id,
    subtotal,
    tax: gst,
    discount: discountAmt,
    total: grandTotal,
    advanceAdjusted: advanceAdjusted > 0 ? advanceAdjusted : undefined,
    notes: billNotes || `IPD Bill — Admission ${admission.admissionNumber}`,
    items: items
      .filter(i => Number(i.quantity) > 0 || Number(i.totalPrice) > 0)
      .map(i => ({
        itemType: i.itemType,
        description: i.description,
        quantity: Number(i.quantity),
        unitPrice: Number(i.unitPrice),
        totalPrice: Number(i.totalPrice),
        radiologyOrderId: i.radiologyOrderId ?? undefined,
        appointmentId: i.appointmentId ?? undefined,
        ambulanceBookingId: i.ambulanceBookingId ?? undefined,
        pharmacyBillId: i.pharmacyBillId ?? undefined,
        otBookingId: i.otBookingId ?? undefined,
        otInvoiceItemId: i.otInvoiceItemId ?? undefined,
      })),
  })

  const handleSaveBill = async () => {
    if (items.length === 0) { notify('Add at least one billing item', 'warning'); return }
    if (items.some(i => !i.description?.trim())) { notify('All items need a description', 'error'); return }
    setSavingBill(true)
    try {
      const payload = buildPayload()
      let finalId = invoiceId
      let savedInvoice
      if (finalId) {
        savedInvoice = await invoiceApi.finalizeIPD(finalId, payload)
      } else {
        savedInvoice = await invoiceApi.create({ ...payload, status: 'UNSETTLED' })
        finalId = savedInvoice.id
        setInvoiceId(finalId)
      }

      // Sync status from server (PAID bill reopened → backend resets to UNPAID)
      if (savedInvoice?.status) setInvoiceStatus(savedInvoice.status)
      setDirty(true)

      // Mark ambulance bookings as paid
      const ambulanceItems = items.filter(i => i.ambulanceBookingId)
      if (ambulanceItems.length > 0) {
        await Promise.allSettled(
          ambulanceItems.map(i => ambulanceApi.updateStatus(i.ambulanceBookingId, { paymentStatus: 'PAID' }))
        )
      }

      const wasReopened = invoiceStatus === 'PAID' || invoiceStatus === 'SETTLED'
      notify(
        wasReopened
          ? 'Bill reopened with new charges — collect outstanding balance'
          : 'Bill saved — collect payment when ready',
        'success'
      )
      setPayAmount(String(Math.round(balanceDue)))
    } catch (err) {
      notify(err?.response?.data?.message || 'Failed to save bill', 'error')
    } finally {
      setSavingBill(false)
    }
  }

  const handleCollectPayment = async () => {
    const amt = Number(payAmount)
    if (!amt || amt <= 0) { notify('Enter a valid amount', 'warning'); return }
    if (!invoiceId) { notify('Save the bill first before collecting payment', 'warning'); return }
    if (items.length === 0) { notify('Add at least one billing item', 'warning'); return }
    if (items.some(i => !i.description?.trim())) { notify('All items need a description', 'error'); return }
    setCollectingPayment(true)
    try {
      // Atomic: send current bill items + payment in one request.
      // Backend updates items, resets PAID→UNPAID if needed, records payment, sets status.
      const result = await invoiceApi.collectAndSave(invoiceId, {
        ...buildPayload(),
        amount: amt,
        paymentMethod: payMethod,
        // Send whatever was selected — backend already handles null gracefully.
        bankAccountId: payBankAccountId || null,
        collectedBy: user?.name || null,
      })

      const newPayment = { id: Date.now(), amount: amt, paymentMethod: payMethod, paidAt: new Date().toISOString() }
      setExistingPayments(prev => [...prev, newPayment])
      setDirty(true)

      // Trust the server's authoritative paid amount over our local optimistic sum —
      // payments can be recorded from multiple places (admit-time advance, ambulance
      // auto-merge, this modal) so the local existingPayments tally can drift.
      const serverPaidAmount = Number(result?.paidAmount ?? 0)
      const serverTotal = Number(result?.total ?? grandTotal)
      const serverStatus = result?.status
      if (serverStatus) setInvoiceStatus(serverStatus)

      // Authoritative balance: total - paidAmount - advance (server tracks all
      // three atomically). Advance counts toward "fully paid" because the
      // patient's money already sits with the hospital — but the notification
      // message below is explicit about that so staff don't think a ₹350 cash
      // payment alone settled a ₹1500 bill.
      const serverAdvance = Number(result?.advanceAdjusted ?? 0)
      const trueBalance = Math.max(0, serverTotal - serverPaidAmount - serverAdvance)
      const isFullySettled = (serverStatus === 'SETTLED' || serverStatus === 'PAID') && trueBalance <= 0
      const inr = n => `₹${Number(n).toLocaleString('en-IN')}`

      if (isFullySettled) {
        // Breakdown so staff can see what made the bill settle — cash alone, or
        // cash plus an existing advance. Without this, partial cash on top of a
        // big advance looks like a bug.
        const parts = []
        if (serverPaidAmount > 0) parts.push(`${inr(serverPaidAmount)} cash`)
        if (serverAdvance > 0)    parts.push(`${inr(serverAdvance)} advance`)
        const breakdown = parts.length > 0 ? ` (${parts.join(' + ')})` : ''
        notify(`Bill of ${inr(serverTotal)} fully covered${breakdown} — patient can be discharged`, 'success')
        onFinalized()
      } else if (trueBalance <= 0 && serverStatus !== 'SETTLED' && serverStatus !== 'PAID') {
        // Local math says balance is zero but server didn't mark settled — surface the
        // discrepancy instead of silently closing or silently lying to the user.
        notify(`${inr(amt)} recorded. Server status: ${serverStatus}. Refresh to verify.`, 'warning')
        setPayAmount('')
      } else {
        notify(`${inr(amt)} recorded. Balance remaining: ${inr(trueBalance)}`, 'success')
        setPayAmount(String(Math.round(trueBalance)))
      }
    } catch (err) {
      notify(err?.response?.data?.message || 'Payment failed — please try again', 'error')
    } finally {
      setCollectingPayment(false)
    }
  }

  const eligibleAccounts = accountsForMethod(bankAccounts, payMethod)
  const needsBankAccount = (PAYMENT_METHOD_TO_ACCOUNT_TYPES[payMethod] || []).length > 0
  const isCash = (admission.paymentCategory || 'CASH') === 'CASH'

  // ── Collect Payment form (shared between Cash and Credit early-collect) ──────
  const collectFormJSX = (
    <div className="hms-form-rows">
      <div className="hms-form-grid is-2col">
        <div className="hms-form-group">
          <label className="hms-label">Amount (₹)</label>
          <input
            type="number"
            min="0"
            step="1"
            className="hms-input"
            value={payAmount}
            onChange={e => setPayAmount(e.target.value)}
            placeholder={String(Math.round(balanceDue))}
          />
        </div>
        <div className="hms-form-group">
          <label className="hms-label">Payment Method</label>
          <SearchableSelect
            className="hms-input"
            value={payMethod}
            onChange={val => {
              setPayMethod(val)
              const eligible = accountsForMethod(bankAccounts, val)
              const def = eligible.find(a => a.isDefault) ?? eligible[0]
              setPayBankAccountId(def ? def.id : '')
            }}
            clearable={false}
            searchable={false}
            options={PAYMENT_METHODS.map(m => ({ value: m, label: m }))}
          />
        </div>
      </div>
      {needsBankAccount && eligibleAccounts.length === 0 && (
        <div className="hms-finalize-alert is-amber">
          <AlertCircle className="hms-finalize-alert__icon w-3.5 h-3.5" />
          <p className="m-0">
            No {payMethod === 'Cash' ? 'CASH' : 'SAVINGS / CURRENT'} account found. Configure banks in the Finance app to track this payment.
          </p>
        </div>
      )}
      {needsBankAccount && eligibleAccounts.length > 0 && (
        <div className="hms-form-group">
          <label className="hms-label flex items-center gap-1.5">
            <Landmark className="w-3 h-3" /> Credit to
            <span className="hms-inv-pay-method-hint">
              ({payMethod === 'Cash' ? 'CASH only' : 'SAVINGS / CURRENT only'})
            </span>
          </label>
          <SearchableSelect
            className="hms-input"
            value={payBankAccountId}
            onChange={setPayBankAccountId}
            clearable={false}
            options={eligibleAccounts.map(a => ({ value: a.id, label: a.accountName }))}
          />
        </div>
      )}
      {balanceDue > 0 && (
        <div className="hms-pay-balance-row">
          <span className="hms-pay-balance-row__label">Balance due</span>
          <span className="hms-pay-balance-row__amt">{fmt(balanceDue)}</span>
        </div>
      )}
      {/* Sprint 2b: settled-claim deduction classification, beside the figure —
          never subtracted from it (the residual is already in balanceDue). */}
      <InvoiceDeductionNote claim={invoiceClaim} />
      {balanceDue > 0 && claimExpected > 0 && (
        <>
          <div className="hms-pay-claim-row">
            <span>Expected from {invoiceClaim.payerName || 'insurer'} (claim approved)</span>
            <span>−{fmt(claimExpected)}</span>
          </div>
          <div className="hms-pay-claim-row is-share">
            <span>Patient&apos;s share to collect</span>
            <span>{fmt(patientShare)}</span>
          </div>
        </>
      )}
      {balanceDue > 0 && invoiceClaim && ['DRAFT', 'PRE_AUTH', 'SUBMITTED'].includes(invoiceClaim.status) && (
        <div className="hms-pay-claim-row is-pending">
          <span>Claim {invoiceClaim.status === 'SUBMITTED' ? 'submitted to' : 'in progress with'} {invoiceClaim.payerName || 'insurer'} — decision pending</span>
          <span>{fmt(Number(invoiceClaim.claimedAmount || 0))}</span>
        </div>
      )}
    </div>
  )

  return (
    <div className="zu-modal-overlay">
      <div className="zu-modal is-full">

        {/* ── Header ── */}
        <div className="zu-modal-header-row">
          <div>
            <h2 className="hms-cmodal__title flex items-center gap-2">
              <Receipt className="w-4 h-4 text-info" /> IPD Bill
            </h2>
            <p className="hms-cmodal__subtitle">
              {admission.patientName} · {fmtId(admission.admissionNumber)}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {(invoiceStatus === 'PAID' || invoiceStatus === 'SETTLED') && (
              <span className="hms-badge is-success">
                Settled
              </span>
            )}
            {(invoiceStatus === 'PARTIAL' || invoiceStatus === 'UNSETTLED') && (
              <span className="hms-badge is-warning">
                Not Settled
              </span>
            )}
            <button onClick={() => onClose(dirty)} className="zu-modal-close">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* ── Body ── */}
        {loadingBill ? (
          <div className="hms-loader-stack">
            <Spinner className="w-8 h-8 zu-spinner text-info" />
            <p className="text-13 font-medium text-gray-600">Loading bill and pending charges…</p>
          </div>
        ) : (
          <div className="hms-finalize-layout">
            <div className="hms-finalize-cols">

            {/* ════ LEFT PANEL ════ */}
            <div className="hms-finalize-cols__main">

              {/* Left sub-header */}
              <div className="hms-finalize-subhead">
                <p className="hms-finalize-subhead__title">Bill Items</p>
                <button onClick={addBlankItem} className="zu-btn-secondary is-sm">
                  <Plus className="w-3.5 h-3.5" /> Add Item
                </button>
              </div>

              {/* Alerts */}
              <div className="shrink-0">
                {chargeLoadWarnings.length > 0 && (
                  <div className="hms-finalize-alert is-amber">
                    <AlertCircle className="hms-finalize-alert__icon w-4 h-4" />
                    <p className="m-0">
                      Couldn't load charges from {chargeLoadWarnings.join(' and ')} — they may be
                      <strong> missing from this bill</strong>. Reopen the bill to retry before finalizing.
                    </p>
                  </div>
                )}
                {hasOpdCarryOver && (
                  <div className="hms-finalize-alert is-info">
                    <Stethoscope className="hms-finalize-alert__icon w-4 h-4" />
                    <p className="m-0">
                      OPD → IPD: consultation charge carried over from the originating OPD visit.
                    </p>
                  </div>
                )}
                {hasZeroPrice && (
                  <div className="hms-finalize-alert is-amber">
                    <AlertCircle className="hms-finalize-alert__icon w-4 h-4" />
                    <p className="m-0">
                      Some items have ₹0 — check radiology charges or add unit price manually.
                    </p>
                  </div>
                )}
              </div>

              {/* Items table */}
              <div>
                {items.length === 0 ? (
                  <div className="hms-finalize-empty">
                    <p className="hms-finalize-empty__title">No charges detected</p>
                    <p className="hms-finalize-empty__sub">Add items manually above</p>
                  </div>
                ) : (
                  <table className="hms-finalize-table">
                    <thead>
                      <tr>
                        <th className="is-no">No</th>
                        <th className="is-type">Type</th>
                        <th>Description</th>
                        <th className="is-center is-qty">Qty</th>
                        <th className="is-right is-unit">Unit ₹</th>
                        <th className="is-right is-total">Total</th>
                        <th className="is-action" />
                      </tr>
                    </thead>
                    <tbody>
                      {items.map((item, idx) => (
                        <tr
                          key={item.key}
                          className={item.fromOpd ? 'is-opd' : ''}
                        >
                          <td className="is-no">{idx + 1}</td>
                          <td>
                            <SearchableSelect
                              value={item.itemType ?? 'CUSTOM'}
                              onChange={val => updateItem(item.key, { itemType: val })}
                              clearable={false}
                              searchable={false}
                              className="hms-finalize-table__type-select"
                              options={Object.keys(TYPE_META).map(k => ({ value: k, label: TYPE_META[k]?.label || k }))}
                            />
                          </td>
                          <td>
                            <div className="hms-finalize-table__desc-wrap">
                              {item.fromOpd && (
                                <span className="hms-finalize-table__opd-badge">OPD</span>
                              )}
                              <input
                                className="hms-finalize-table__input"
                                placeholder="Description…"
                                value={item.description}
                                onChange={e => updateItem(item.key, { description: e.target.value })}
                              />
                            </div>
                          </td>
                          <td>
                            <input
                              type="number"
                              min={1}
                              className="hms-finalize-table__input is-center no-spin"
                              value={item.quantity}
                              onChange={e => updateItem(item.key, { quantity: parseInt(e.target.value) || 1 })}
                            />
                          </td>
                          <td>
                            <input
                              type="number"
                              min={0}
                              step="0.01"
                              className="hms-finalize-table__input is-right"
                              value={item.unitPrice}
                              onChange={e => updateItem(item.key, { unitPrice: parseFloat(e.target.value) || 0 })}
                            />
                          </td>
                          <td className="is-total">
                            <span className="hms-finalize-table__total">{fmt(item.totalPrice || 0)}</span>
                          </td>
                          <td>
                            <button
                              onClick={() => removeItem(item.key)}
                              className="hms-finalize-table__remove"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>

              {/* Totals footer */}
              <div className="hms-finalize-totals">
                <div className="hms-finalize-totals__row">
                  <span>Subtotal</span>
                  <span className="font-semibold">{fmt(subtotal)}</span>
                </div>
                <div className="hms-finalize-totals__row">
                  <span>Discount (%)</span>
                  <input
                    type="number"
                    min={0}
                    max={100}
                    className="hms-finalize-discount-input"
                    value={discountPct}
                    onChange={e => setDiscountPct(Math.min(100, parseFloat(e.target.value) || 0))}
                  />
                </div>
                {discountAmt > 0 && (
                  <div className="hms-finalize-totals__row is-discount">
                    <span>Discount</span>
                    <span>-{fmt(discountAmt)}</span>
                  </div>
                )}
                {medicineSubtotal > 0 && (
                  <div className="hms-finalize-totals__row">
                    <span>GST on medicines (18%)</span>
                    <span>{fmt(gst)}</span>
                  </div>
                )}
                <div className="hms-finalize-totals__row is-grand">
                  <span>Grand Total</span>
                  <span>{fmt(grandTotal)}</span>
                </div>
                {advanceAdjusted > 0 && (
                  <div className="hms-finalize-totals__row is-advance">
                    <span className="flex items-center gap-1"><Wallet className="w-3.5 h-3.5" /> Advance Credit</span>
                    <span>-{fmt(advanceAdjusted)}</span>
                  </div>
                )}
                {advanceRemaining > 0 && (
                  <div className="hms-finalize-totals__row is-advance-left">
                    <span>Advance left after this bill</span>
                    <span>{fmt(advanceRemaining)}</span>
                  </div>
                )}
                {totalCashPaid > 0 && (
                  <div className="hms-finalize-totals__row">
                    <span>Paid so far</span>
                    <span>-{fmt(totalCashPaid)}</span>
                  </div>
                )}
                <div className="hms-finalize-totals__row is-balance">
                  <span>Balance Due</span>
                  <span>{fmt(balanceDue)}</span>
                </div>
              </div>
            </div>

            {/* ════ RIGHT PANEL ════ */}
            <div className="hms-finalize-cols__side">

              {/* Right sub-header */}
              <div className="hms-finalize-subhead">
                <p className="hms-finalize-subhead__title">Payment details</p>
              </div>

              <div className="hms-finalize-side">

                {/* 1. Payment category badge */}
                {isCash ? (
                  <div className="hms-pay-cat-pill is-cash">
                    <Wallet className="w-3.5 h-3.5 shrink-0" />
                    <span>
                      Cash · Pay during stay
                    </span>
                  </div>
                ) : (
                  <div className="hms-pay-cat-pill is-credit">
                    <Clock className="w-3.5 h-3.5 shrink-0" />
                    <span>
                      Credit · Payment due at discharge
                    </span>
                  </div>
                )}

                {/* 2. Advance Credits */}
                {advances.length > 0 && (
                  <div className="hms-advance-block">
                    <div className="hms-advance-block__head">
                      <Wallet className="w-3.5 h-3.5 shrink-0 text-success" />
                      <p className="hms-advance-block__head-label">
                        Advance Credits — {fmt(totalAdvance)} available
                        {advanceAdjusted > 0 && ` · ${fmt(advanceRemaining)} left after this bill`}
                      </p>
                    </div>
                    <div className="hms-advance-block__list">
                      {advances.map(a => {
                        const remaining = Math.max(0, Number(a.amount) - Number(a.appliedAmount || 0))
                        return (
                          <div key={a.id} className="hms-advance-row">
                            <div>
                              <span className="hms-advance-row__id">{fmtId(a.receiptNumber)}</span>
                              <span className="hms-advance-row__source">
                                {a.source} · {a.paymentMethod}
                              </span>
                            </div>
                            <span className="hms-advance-row__amt">
                              {fmt(remaining)} available
                            </span>
                          </div>
                        )
                      })}
                    </div>
                  </div>
                )}

                {/* 3. Payment History */}
                {existingPayments.length > 0 && (
                  <div className="hms-pay-history">
                    <p className="hms-pay-history__title">Payment History</p>
                    <div className="flex flex-col gap-3">
                      {existingPayments.map((p, i) => (
                        <div key={p.id ?? i} className="hms-pay-history__row">
                          <p className="hms-pay-history__time">
                            {fmtTime(p.paidAt)}
                          </p>
                          <div className="hms-pay-history__body">
                            <p className="hms-pay-history__method">{p.paymentMethod}</p>
                            {(p.collectedByName || p.collectedBy) && (
                              <p className="hms-pay-history__method">· {p.collectedByName || p.collectedBy}</p>
                            )}
                          </div>
                          <p className="hms-pay-history__amt">{fmt(p.amount)}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* 4a. CASH patients — Collect Payment */}
                {isCash && (
                  <div>
                    <p className="hms-pay-section-label">
                      <IndianRupee className="w-3.5 h-3.5" /> Amount Paid
                    </p>
                    {collectFormJSX}
                  </div>
                )}

                {/* 4b. CREDIT patients — Deferred notice + optional early collect */}
                {!isCash && (
                  <div className="flex flex-col gap-3">
                    <div className="hms-pay-defer-note">
                      <p className="hms-pay-defer-note__text">
                        Payment deferred to discharge. The full balance will be collected when the patient is discharged.
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => setShowEarlyCollect(v => !v)}
                      className="hms-pay-early-toggle"
                    >
                      {showEarlyCollect ? '− Hide early payment' : '+ Collect early payment'}
                    </button>
                    {showEarlyCollect && (
                      <div className="pt-1">
                        <p className="hms-pay-section-label">
                          <IndianRupee className="w-3.5 h-3.5" /> Amount Paid
                        </p>
                        {collectFormJSX}
                      </div>
                    )}
                  </div>
                )}

                {/* 5. Bill Notes */}
                <div className="hms-form-group">
                  <label className="hms-label">Bill Notes (optional)</label>
                  <input
                    className="hms-input"
                    placeholder={`IPD Bill — Admission ${fmtId(admission.admissionNumber)}`}
                    value={billNotes}
                    onChange={e => setBillNotes(e.target.value)}
                  />
                </div>

              </div>
            </div>

            </div>
          </div>
        )}

        {/* ── Footer ── */}
        {!loadingBill && (
          <div className="hms-finalize-footer">
            <button type="button" onClick={() => onClose(dirty)} className="zu-btn-cancel">Close</button>
            <div className="flex items-center gap-2">
              <button
                onClick={handleSaveBill}
                disabled={savingBill || items.length === 0}
                className="zu-btn-secondary flex items-center gap-2"
              >
                {savingBill ? <Spinner className="w-4 h-4 zu-spinner" /> : <Receipt className="w-4 h-4" />}
                {savingBill ? 'Saving…' : 'Save Bill'}
              </button>
              {(isCash || showEarlyCollect) && (
                <button
                  onClick={handleCollectPayment}
                  disabled={collectingPayment || !Number(payAmount)}
                  className="zu-btn-primary flex items-center gap-2"
                >
                  {collectingPayment
                    ? <><Spinner className="w-4 h-4 zu-spinner" /> Recording…</>
                    : <><IndianRupee className="w-4 h-4" /> Amount Paid</>

                  }
                </button>
              )}
            </div>
          </div>
        )}

      </div>
    </div>
  )
}
